title: Mahnoor's blog
author: Mahnoor Asghar
email: masghar.bese15seecs@seecs.edu.pk
description: > # this means to ignore newlines until "baseurl:"
  Hi! This blog will be used to learn to use Github pages with Jekyll.

# social links
twitter_username: mahnoorasghar01 # DO NOT include the @ character, or else the build will fail!
github_username: MahnoorAsghar # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
